const categorias: Map<string, string[]> = new Map();

categorias.set('Animais', [
    'Abelha',
    'Águia',
    'Arara',
    'Aranha',       
    'Bacalhau',        
    'Barata',
    'Baleia',        
    'Borboleta',
    'Cachorro',
    'Camarão',
    'Camelo',
    'Canguru',
    'Cavalo',
    'Centopéia',
    'Cisne',
    'Cobra',
    'Crocodilo',
    'Coruja',
    'Elefante',
    'Escorpião',
    'Falcão',
    'Flamingo',
    'Formiga',
    'Gafanhoto',
    'Galinha',
    'Gambá',
    'Gato',
    'Girafa',
    'Golfinho',
    'Gorila',
    'Hiena',
    'Hipopótamo',
    'Jacaré',
    'Lagarto',
    'Leão',
    'Macaco',
    'Mamute',
    'Minhoca',
    'Morcego',
    'Mosca',
    'Ovelha',
    'Panda',
    'Pato',
    'Piranha',
    'Porco',
    'Preguiça',
    'Rato',
    'Siri',
    'Tartaruga',
    'Tigre',
    'Touro',
    'Vaca',
    'Veado',
    'Zebra',
]);


categorias.set('Atores', [
    'Al Pacino',
    'Arnold Schwazenegger',
    'Adam Sandler',
    'Adriana Esteves',
    'Al Pacino',
    'Amy Adams',
    'Aaron Paul',
    'Angelina Jolie',
    'Anne Hathaway',
    'Andrew Garfield',
    'Antonio Banderas',
    'Ashton Kutcher',
    'Anya Taylor-Joy',
    'Brad Pitt',
    'Bruna Marquezine',
    'Bruno Gagliasso',
    'Bruno Mazzeo',
    'Bruce Lee',
    'Bruce Willys',
    'Ben Affleck',
    'Benedict Cumberbatch',
    'Benedict Wong',
    'Bryan Cranston',
    'Caio Castro',
    'Cameron Diaz',
    'Caroline Dieckman',
    'Cauã Reymond',
    'Chay Suede',
    'Chris Rock',
    'Chris Evans',
    'Chris Hemsworth',
    'Chris Pratt',
    'Christian Bale',
    'Charlie Cox',
    'Chadwick Boseman',
    'Chico Anísio',
    'Courtney Cox',
    'David Schwimmer',
    'Deborah Secco',
    'Dira Paes',
    'Diego Luna',
    'Daniel Radcliffe',
    'Denzel Washington',
    'Dwayne Johnson',
    'Drew Barrymore',
    'Eddie Murphy',
    'Emilia Clarke',
    'Emily Blunt',
    'Emma Roberts',
    'Emma Watson',
    'Evandro Mesquita',
    'Fabiana Karla',
    'Fábio Assunção',
    'Fernanda Montenegro',
    'Fernanda Paes Leme',
    'Fernanda Souza',
    'Fernanda Torres',
    'Fiorella Mattheis',
    'Gal Gadot',
    'Grazi Massafera',
    'George Clooney',
    'Heloísa Périssé',
    'Harrison Ford',
    'Henry Cavill',
    'Hilary Duff',
    'Hugh Jackman',
    'Hugo Weaving',
    'Hugh Laurie',
    'Ingrid Guimarães',
    'Ísis Valverde',
    'Isla Fisher',
    'Jesuíta Barbosa',
    'Jackie Chan',
    'Jessica Biel',
    'Jada Pinkett Smith',
    'James McAvoy',
    'Jared Leto',
    'Jean-Claude Van Damme',
    'Jennifer Aniston',
    'Jennifer Garner',
    'Jennifer Lawrence',
    'Jessica Alba',
    'Jessica Chainstain',
    'Jim Carrey',
    'Joey King',
    'John Travolta',
    'Johnny Depp',
    'Jude Law',
    'Julia Roberts',
    'Kaley Cuoco',
    'Keanu Reeves',
    'Keira Knightley',
    'Kristen Bell',
    'Kristen Stewart',
    'Krysten Ritter',
    'Larissa Manoela',
    'Lázaro Ramos',
    'Leandra Leal',
    'Leandro Hassum',
    'Luana Piovani',
    'Lisa Kudrow',
    'Leighton Meester',
    'Leonardo Dicaprio',
    'Lily Collins',
    'Logan Lerman',
    'Marjorie Estiano',
    'Mariana Ximenes',
    'Marina Ruy Barbosa',
    'Marília Pêra',
    'Matthew Perry',
    'Marisa Tomei',
    'Murilo Benício',
    'Margot Robbie',
    'Mark Ruffalo',
    'Matt Damon',
    'Matt LeBlanc',
    'Matthew McConaughey',
    'Megan Fox',
    'Malu Mader',
    'Mila Kunis',
    'Miles Teller',
    'Morgan Freeman',
    'Maggie Smith',
    'Michael B. Jordan',
    'Natalie Portman',
    'Neil Patrick Harris',
    'Nicolas Cage',
    'Nicole Kidman',
    'Orlando Bloom',
    'Paolla Oliveira',
    'Patricia Pillar',
    'Pedro Pascal',
    'Paul Walker',
    'Queen Latifah',
    'Quentin Tarantino',
    'Rachel McAddams',
    'Renato Aragão',
    'Rodrigo Santoro',
    'Robert De Niro',
    'Robert Pattinson',
    'Robin Williams',
    'Ryan Gosling',
    'Ryan Reynolds',
    'Sandra Bullock',
    'Sarah Jessica Parker',
    'Scarlett Johansson',
    'Selton Mello',
    'Sophie Charlotte',
    'Susana Vieira',
    'Sylvester Stallone',
    'Tarcísio Meira',
    'Thiago Lacerda',
    'Tony Ramos',
    'Taron Egerton',
    'Toby Stephens',
    'Tobey Maguire',
    'Tom Cruise',
    'Tom Hiddleston',
    'Tom Holland',
    'Tom Hardy',
    'Vanessa Giácomo',
    'Vin Diesel',
    'Will Ferell',
    'Will Smith',
    'Whoopi Goldberg',
    'Zac Efron',
    'Zendaya Coleman',
    'Zoë Kravitz',
    'Zooey Deschanel', 
]);


categorias.set('Cantores e bandas', [
    'ABBA',
    'AC/DC',
    'Akon',
    'Adele',
    'Avicii',
    'Alan Walker',
    'Aerosmith',
    'Alceu Valença',
    'Adam Levine',
    'Adriana Calcanhotto',
    'Amy Whinehouse',
    'Anavitória',
    'Anitta',
    'Alcione',
    'Arctic Monkeys',
    'Ariana Grande',
    'Audioslave',
    'Aurora',
    'Avril Lavigne',
    'Backstreet Boys',
    'Beyoncé',
    'Beatles',
    'Billie Eilish',
    'Black Eyed Peas',
    'Bob Dylan',
    'Bob Marley',
    'Bon Jovi',
    'Bono',
    'Bruno Mars',
    'BTS',
    'Caetano Veloso',
    'Calvin Harris',
    'Camila Cabello',
    'Cássia Eller',
    'Céline Dion',
    'Chico Buarque',
    'Christina Aguilera',
    'Coldplay',
    'Cigarettes After Sex',
    'Daniela Mercury',
    'David Bowie',
    'Demi Lovato',
    'Djavan',
    'Drake',
    'Dua Lipa',
    'Duda Beat',
    'Daft Punk',
    'É o Tchan',
    'Eddie Vedder',
    'Ed Sheeran',
    'Elis Regina',
    'Elton John',
    'Elvis Presley',
    'Eminem',
    'Evanescence',
    'Exaltassamba',
    'Extreme',
    'Fábio Júnior',
    'Fagner',
    'Fergie',
    'Florence + The Machine',
    'Frank Sinatra',
    'Freddie Mercury',
    'Gabriel, o Pensador',
    'Gaby Amarantos',
    'Gal Costa',
    'Glória Groove',
    'Gretchen',
    `Guns N' Roses`,
    'Gusttavo Lima',
    'Halsey',
    'Imagine Dragons',
    'Iron Maiden',
    'Ivete Sangalo',
    'Iza',
    'Jaden Smith',
    'Jay-Z',
    'James Blunt',
    'Jennifer Lopez',
    'Jessie J',
    'John Legend',
    'John Lennon',
    'Jorge Ben Jor',
    'Justin Bieber',
    'Justin Timberlake',
    'Kanye West',
    'Katy Perry',
    'Kurt Cobain',
    'Lady Gaga',
    'Lana Del Rey',
    'Led Zeppelin',
    'Léo Santana',
    'Lenny Kravitz',
    'Lily Allen',
    'Linkin Park',
    'Ludmilla',
    'Luisa Sonza',
    'Madonna',
    'Mamonas Assassinas',
    'Mano Brown',
    'Marcelo D2',
    'Maria Bethânia',
    'Mariah Carey',
    'Marília Mendonça',
    'Marilyn Manson',
    'Marisa Monte',
    'Maroon 5',
    'Metallica',
    'Michael Jackson',
    'Mick Jagger',
    'Miley Cyrus',
    'Naiara Azevedo',
    'Nando Reis',
    'Ney Matogrosso',
    'Nickelback',
    'Nicki Minaj',
    'Nirvana',
    'O Rappa',
    'Oasis',
    'Os Paralamas do Sucesso',
    'One Direction',
    'OneRepublic',
    'Pabllo Vittar',
    'Paul McCartney',
    'Paula Fernandes',
    'Pearl Jam',
    'Pedro Sampaio',
    'Queen',
    'Raça Negra',
    'R.E.M.',
    'Radiohead',
    'Raimundos',
    'Raul Seixas',
    'Red Hot Chilli Peppers',
    'Rihanna',
    'Rita Lee',
    'Roberto Carlos',
    'Rolling Stones',
    'Sam Smith',
    'Scorpions',
    'Selena Gomez',
    'Seu Jorge',
    'Shakira',
    'Shawn Mendes',
    'Sia',
    'Snoop Dogg',
    'Spice Girls',
    'Taylor Swift',
    'The Doors',
    'The Killers',
    'The Lumineers',
    'The Police',
    'Twenty One Pilots',
    'The Smiths',
    'The Strokes',
    'The Weeknd',
    'The Neighbourhood',
    'Thiaguinho',
    'U2',
    'Wesley Safadão',
    'Woodkid',
    'Zezé Di Camargo e Luciano',
    'Julian Casablancas',
]);


categorias.set('Personalidades brasileiras', [
    'Ana Furtado',
    'Ana Maria Braga',
    'Ana Hickmann',
    'Anitta',
    'André Marques',
    'Bianca Andrade',
    'Bruna Marquezine',
    'Carlinhos Maia',
    'Casimiro',
    'Danilo Gentilli',
    'Dra. Deolane',
    'Eliana',
    'Evaristo Costa',
    'Faustão',
    'Fátima Bernardes',
    'Felipe Castanhari',
    'Felipe Neto',
    'Giovana Ewbank',
    'Gisele Bündchen',
    'GKay',
    'Glória Maria',
    'Gugu Liberato',
    'Hugo Gloss',
    'Jade Picon',
    'João Guilherme',
    'Jojo Todynho',
    'Jô Soares',
    'Juliette Freire',
    'Kéfera Buchmann',
    'Larissa Manoela',
    'Lucas Guedes',
    'Lucas Rangel',
    'Luciano Huck',
    'Luva de Pedreiro',
    'Maisa',
    'Manu Gavassi',
    'Mc Mirella',
    'Marcos Mion',
    'Mari Maria',
    'Pabllo Vittar',
    'Pedro Bial',
    'Tatá Werneck',
    'Tirullipa',
    'Rafa Uccman',
    'Rafa Kalimann',
    'Raul Gil',
    'Rodrigo Faro',
    'Sabrina Sato',
    'Virgínia Fonseca',
    'Viih Tube',
    'Whinderson Nunes',
    'William Bonner',
]);


categorias.set('Personalidades internacionais', [
    'Bella Hadid',
    'Barack Obama',
    'Cara Delevingne',
    'Ellen DeGeneres',
    'Gigi Hadid',
    'Hailey Bieber',
    'James Corden',
    'James Cameron',
    'Jimmy Fallon',
    'Jeremy Clarkson',
    'Jimmy Kimmel',
    'Jeff Bezos',
    'Megan Fox',
    'Ken Block',
    'Kendall Jenner',
    'Khabane Lame',
    'Khloe Kardashian',
    'Kim Kardashian',
    'Kris Jenner',
    'Kylie Jenner',
    'Neil Degrasse Tyson',
    'Oprah Winfrey',
    'Paris Hilton',
    'Simon Cowell',
    'Steve Harvey',
    'Stephen Colbert',
    'George Lucas',
]);


categorias.set('Jogadores de futebol', [
    'Carlos Henrique Casemiro',
    'Cristiano Ronaldo',
    'David Beckham',
    'Daniel Alves',
    'Gabriel Jesus',
    'Gabigol',
    'Gerard Piqué',
    'Ikler Casillas',
    'James Rodríguez',
    'Kaká',
    'Kylian Mbappé',
    'Lionel Messi',
    'Luis Alberto Suárez',
    'Luka Modrić',
    'Neymar',
    'Maradona',
    'Mesut Özil',
    'Mohamed Salah',
    'Pelé',
    'Roberto Carlos',
    'Ronaldinho Fenômeno',
    'Ronaldinho Gaúcho',
    'Romário',
    'Sergio Ramos',
    'Thomas Müller',
    'Zico',
    'Zinédine Zidane',
]);


categorias.set('Personagens da Disney', [
    'Ariel',
    'Alladin',
    'Alice',
    'Andrômeda',
    'Baymax',
    'Bela',
    'Bela Ardomecida',
    'Branca de Neve',
    'Buzz Lightyear',
    'Capitão Gancho',
    'Capitão Jack Sparrow',
    'Cinderela',
    'Conserta Félix Jr.',
    'Cruella de Vil',
    'Detona Ralph',
    'Elsa',
    'Hades',
    'Hércules',
    'Kida',
    'Merida',
    'Mike Wazowski',
    'Mickey Mouse',
    'Minnie Mouse',
    'Milo Thatch',
    'Moana',
    'Mulan',
    'Olaf',
    'Pateta',
    'Peter Pan',
    'Pluto',
    'Pricesa Jasmine',
    'Princesa Tiana',
    'Pocahontas',
    'Rapunzel',
    'Relâmpago Mcqueen',
    'Scar',
    'Stitch',
    'Sininho',
    'Tarzan',
    'Ursinho Pooh',
    'Úrsula',
    'Xerife Woody',
]);


categorias.set('Personagens de desenho animado', [
    'Bart Simpson',
    'Beetty Boop',
    'Bob Esponja',
    'Charlie Brown',
    'Cosmo',
    'Daphne',
    'Docinho',
    'Florzinha',
    'Frajola',
    'Fred Flinstone',
    'Gato Félix',
    'Gasparzinho',
    'Homer Simpson',
    'He-Man',
    'Jerry',
    'Lindinha',
    'Lisa Simpson',
    'Lula Molusco',
    'Macaco Louco',
    'Magali',
    'Mestre dos Magos',
    'Mônica',
    'Pantera cor-de-rosa',
    'Patolino',
    'Patrick Estrela',
    'Pernalonga',
    'Pica-Pau',
    'Piu-Piu',
    'Popeye',
    'Salsicha',
    'Scooby-Doo',
    'Timmy Turner',
    'Ursinho Pooh',
    'Velma',
    'Vingador',
    'Zé Colmeia',
]);


export {categorias};