const categorias: Map<string, string[]> = new Map();

categorias.set('Animais', [
  'Abelha',
  'Águia',
  'Arara',
  'Anta',
  'Antílope',
  'Aranha',
  'Avestruz',
  'Atum',
  'Bacalhau',
  'Barata',
  'Baleia',
  'Beija-Flor',
  'Besouro',
  'Borboleta',
  'Boi',
  'Bode',
  'Boto-cor-de-rosa',
  'Cachorro',
  'Caranguejo',
  'Castor',
  'Camarão',
  'Camelo',
  'Canguru',
  'Cavalo',
  'Cavalo-Marinho',
  'Centopéia',
  'Cisne',
  'Cobra',
  'Crocodilo',
  'Coruja',
  'Doninha',
  'Dromedário',
  'Dragão',
  'Dragão-de-Komodo',
  'Elefante',
  'Escorpião',
  'Esquilo',
  'Equidna',
  'Égua',
  'Enguia',
  'Falcão',
  'Flamingo',
  'Formiga',
  'Foca',
  'Fuinha',
  'Gafanhoto',
  'Galinha',
  'Gambá',
  'Gato',
  'Girafa',
  'Golfinho',
  'Gorila',
  'Gaivota',
  'Ganso',
  'Harpia',
  'Hiena',
  'Hipopótamo',
  'Jacaré',
  'Jumento',
  'Joaninha',
  'João-de-barro',
  'Lagarto',
  'Leão',
  'Lagosta',
  'Lagartixa',
  'Macaco',
  'Mamute',
  'Minhoca',
  'Morcego',
  'Mosca',
  'Ovelha',
  'Ornitorrinco',
  'Onça-pintada',
  'Panda',
  'Pato',
  'Piranha',
  'Porco',
  'Peixe-Boi',
  'Preguiça',
  'Pinguim',
  'Papagaio',
  'Rato',
  'Rena',
  'Raposa',
  'Rinoceronte',
  'Siri',
  'Sapo',
  'Suricato',
  'Sardinha',
  'Tatu',
  'Tubarão',
  'Tucano',
  'Tartaruga',
  'Tigre',
  'Touro',
  'Vaca',
  'Vespa',
  'Veado',
  'Zebra',
  'Zangão',
]);

categorias.set('Objetos', [
  'Abajur',
  'Agulha',
  'Algema',
  'Âncora',
  'Anel',
  'Apito',
  'Balança',
  'Bambolê',
  'Bandeira',
  'Bengala',
  'Berço',
  'Bicicleta',
  'Boneca',
  'Brinco',
  'Bússola',
  'Cadeado',
  'Cadeira',
  'Caderno',
  'Calculadora',
  'Campainha',
  'Caneta',
  'Capa',
  'Capacete',
  'Celular',
  'Colher',
  'Computador',
  'Copo',
  'Dado',
  'Dentadura',
  'Desodorante',
  'Despertador',
  'Diamante',
  'Diário',
  'Edredom',
  'Elástico',
  'Envelope',
  'Escada',
  'Escova',
  'Espelho',
  'Esponja',
  'Estátua',
  'Extintor',
  'Faca',
  'Farol',
  'Flauta',
  'Flecha',
  'Fogão',
  'Frigideira',
  'Frigobar',
  'Gaiola',
  'Garfo',
  'Garrafa',
  'Geladeira',
  'Gravata',
  'Hidratante',
  'Impressora 3D',
  'Isopor',
  'Isqueiro',
  'Janela',
  'Jaqueta',
  'Karaokê',
  'Lâmpada',
  'Lancheira',
  'Lanterna',
  'Lençol',
  'Livro',
  'Lixeira',
  'Mamadeira',
  'Martelo',
  'Microfone',
  'Mochila',
  'Motor',
  'Nave',
  'Navio',
  'Óculos',
  'Ouro',
  'Panela',
  'Papel',
  'Peruca',
  'Piano',
  'Pincel',
  'Prato',
  'Pulseira',
  'Quadro',
  'Quimono',
  'Rádio',
  'Relógio',
  'Revista',
  'Sabonete',
  'Sacola',
  'Sapato',
  'Secador',
  'Short',
  'Skate',
  'Sombrinha',
  'Tábua',
  'Tambor',
  'Telefone',
  'Tênis',
  'Tesoura',
  'Uniforme',
  'Ventilador',
  'Violão',
  'Violino',
  'Xadrez',
  'Xampu',
]);

categorias.set('Atores', [
  'Al Pacino',
  'Arnold Schwarzenegger',
  'Adam Sandler',
  'Adriana Esteves',
  'Amy Adams',
  'Aaron Paul',
  'Angelina Jolie',
  'Anne Hathaway',
  'Andrew Garfield',
  'Antonio Banderas',
  'Ashton Kutcher',
  'Anya Taylor-Joy',
  'Brad Pitt',
  'Bruna Marquezine',
  'Bruno Gagliasso',
  'Bruno Mazzeo',
  'Bruce Lee',
  'Bruce Willys',
  'Ben Affleck',
  'Benedict Cumberbatch',
  'Benedict Wong',
  'Bryan Cranston',
  'Caio Castro',
  'Cameron Diaz',
  'Caroline Dieckman',
  'Cauã Reymond',
  'Chay Suede',
  'Chris Rock',
  'Chris Evans',
  'Chris Hemsworth',
  'Chris Pratt',
  'Christian Bale',
  'Charlie Cox',
  'Chadwick Boseman',
  'Chico Anísio',
  'Courtney Cox',
  'David Schwimmer',
  'Deborah Secco',
  'Dira Paes',
  'Diego Luna',
  'Daniel Radcliffe',
  'Denzel Washington',
  'Dwayne Johnson',
  'Drew Barrymore',
  'Eddie Murphy',
  'Emilia Clarke',
  'Emily Blunt',
  'Emma Roberts',
  'Emma Watson',
  'Evandro Mesquita',
  'Fabiana Karla',
  'Fábio Assunção',
  'Fernanda Montenegro',
  'Fernanda Paes Leme',
  'Fernanda Souza',
  'Fernanda Torres',
  'Fiorella Mattheis',
  'Gal Gadot',
  'Grazi Massafera',
  'George Clooney',
  'Heloísa Périssé',
  'Harrison Ford',
  'Henry Cavill',
  'Hilary Duff',
  'Hugh Jackman',
  'Hugo Weaving',
  'Hugh Laurie',
  'Ingrid Guimarães',
  'Ísis Valverde',
  'Isla Fisher',
  'Jesuíta Barbosa',
  'Jackie Chan',
  'Jessica Biel',
  'Jada Pinkett Smith',
  'James McAvoy',
  'Jared Leto',
  'Jean-Claude Van Damme',
  'Jennifer Aniston',
  'Jennifer Garner',
  'Jennifer Lawrence',
  'Jessica Alba',
  'Jessica Chainstain',
  'Jim Carrey',
  'Joey King',
  'John Travolta',
  'Johnny Depp',
  'Jude Law',
  'Julia Roberts',
  'Kaley Cuoco',
  'Keanu Reeves',
  'Keira Knightley',
  'Kristen Bell',
  'Kristen Stewart',
  'Krysten Ritter',
  'Larissa Manoela',
  'Lázaro Ramos',
  'Leandra Leal',
  'Leandro Hassum',
  'Luana Piovani',
  'Lisa Kudrow',
  'Leighton Meester',
  'Leonardo Dicaprio',
  'Lily Collins',
  'Logan Lerman',
  'Marjorie Estiano',
  'Mariana Ximenes',
  'Marina Ruy Barbosa',
  'Marília Pêra',
  'Matthew Perry',
  'Marisa Tomei',
  'Murilo Benício',
  'Margot Robbie',
  'Mark Ruffalo',
  'Matt Damon',
  'Matt LeBlanc',
  'Matthew McConaughey',
  'Megan Fox',
  'Malu Mader',
  'Mila Kunis',
  'Miles Teller',
  'Morgan Freeman',
  'Maggie Smith',
  'Michael B. Jordan',
  'Natalie Portman',
  'Neil Patrick Harris',
  'Nicolas Cage',
  'Nicole Kidman',
  'Orlando Bloom',
  'Paolla Oliveira',
  'Patricia Pillar',
  'Pedro Pascal',
  'Paul Walker',
  'Queen Latifah',
  'Quentin Tarantino',
  'Rachel McAddams',
  'Renato Aragão',
  'Rodrigo Santoro',
  'Robert De Niro',
  'Robert Pattinson',
  'Robin Williams',
  'Ryan Gosling',
  'Ryan Reynolds',
  'Sandra Bullock',
  'Sarah Jessica Parker',
  'Scarlett Johansson',
  'Selton Mello',
  'Sophie Charlotte',
  'Susana Vieira',
  'Sylvester Stallone',
  'Tarcísio Meira',
  'Thiago Lacerda',
  'Tony Ramos',
  'Taron Egerton',
  'Toby Stephens',
  'Tobey Maguire',
  'Tom Cruise',
  'Tom Hiddleston',
  'Tom Holland',
  'Tom Hardy',
  'Vanessa Giácomo',
  'Vin Diesel',
  'Will Ferell',
  'Will Smith',
  'Whoopi Goldberg',
  'Zac Efron',
  'Zendaya Coleman',
  'Zoë Kravitz',
  'Zooey Deschanel',
]);

categorias.set('Cantores e bandas', [
  'ABBA',
  'AC/DC',
  'Akon',
  'Adele',
  'Avicii',
  'Alan Walker',
  'Aerosmith',
  'Alceu Valença',
  'Adam Levine',
  'Adriana Calcanhotto',
  'Amy Whinehouse',
  'Anavitória',
  'Anitta',
  'Alcione',
  'Arctic Monkeys',
  'Ariana Grande',
  'Audioslave',
  'Aurora',
  'Avril Lavigne',
  'Backstreet Boys',
  'Beyoncé',
  'Beatles',
  'Billie Eilish',
  'Black Eyed Peas',
  'Bob Dylan',
  'Bob Marley',
  'Bon Jovi',
  'Bono',
  'Bruno Mars',
  'BTS',
  'Caetano Veloso',
  'Calvin Harris',
  'Camila Cabello',
  'Cássia Eller',
  'Céline Dion',
  'Chico Buarque',
  'Christina Aguilera',
  'Coldplay',
  'Cigarettes After Sex',
  'Daniela Mercury',
  'David Bowie',
  'Demi Lovato',
  'Djavan',
  'Drake',
  'Dua Lipa',
  'Duda Beat',
  'Daft Punk',
  'É o Tchan',
  'Eddie Vedder',
  'Ed Sheeran',
  'Elis Regina',
  'Elton John',
  'Elvis Presley',
  'Eminem',
  'Evanescence',
  'Exaltassamba',
  'Extreme',
  'Fábio Júnior',
  'Fagner',
  'Fergie',
  'Florence + The Machine',
  'Frank Sinatra',
  'Freddie Mercury',
  'Gabriel, o Pensador',
  'Gaby Amarantos',
  'Gal Costa',
  'Glória Groove',
  'Gretchen',
  `Guns N' Roses`,
  'Gusttavo Lima',
  'Halsey',
  'Imagine Dragons',
  'Iron Maiden',
  'Ivete Sangalo',
  'Iza',
  'Jaden Smith',
  'Jay-Z',
  'James Blunt',
  'Jennifer Lopez',
  'Jessie J',
  'John Legend',
  'John Lennon',
  'Jorge Ben Jor',
  'Justin Bieber',
  'Justin Timberlake',
  'Kanye West',
  'Katy Perry',
  'Kurt Cobain',
  'Lady Gaga',
  'Lana Del Rey',
  'Led Zeppelin',
  'Léo Santana',
  'Lenny Kravitz',
  'Lily Allen',
  'Linkin Park',
  'Ludmilla',
  'Luisa Sonza',
  'Madonna',
  'Mamonas Assassinas',
  'Mano Brown',
  'Marcelo D2',
  'Maria Bethânia',
  'Mariah Carey',
  'Marília Mendonça',
  'Marilyn Manson',
  'Marisa Monte',
  'Maroon 5',
  'Metallica',
  'Michael Jackson',
  'Mick Jagger',
  'Miley Cyrus',
  'Naiara Azevedo',
  'Nando Reis',
  'Ney Matogrosso',
  'Nickelback',
  'Nicki Minaj',
  'Nirvana',
  'O Rappa',
  'Oasis',
  'Os Paralamas do Sucesso',
  'One Direction',
  'OneRepublic',
  'Pabllo Vittar',
  'Paul McCartney',
  'Paula Fernandes',
  'Pearl Jam',
  'Pedro Sampaio',
  'Queen',
  'Raça Negra',
  'R.E.M.',
  'Radiohead',
  'Raimundos',
  'Raul Seixas',
  'Red Hot Chilli Peppers',
  'Rihanna',
  'Rita Lee',
  'Roberto Carlos',
  'Rolling Stones',
  'Sam Smith',
  'Scorpions',
  'Selena Gomez',
  'Seu Jorge',
  'Shakira',
  'Shawn Mendes',
  'Sia',
  'Snoop Dogg',
  'Spice Girls',
  'Taylor Swift',
  'The Doors',
  'The Killers',
  'The Lumineers',
  'The Police',
  'Twenty One Pilots',
  'The Smiths',
  'The Strokes',
  'The Weeknd',
  'The Neighbourhood',
  'Thiaguinho',
  'U2',
  'Wesley Safadão',
  'Woodkid',
  'Zezé Di Camargo e Luciano',
  'Julian Casablancas',
]);

categorias.set('Personalidades brasileiras', [
  'Ana Furtado',
  'Ana Maria Braga',
  'Ana Hickmann',
  'Anitta',
  'André Marques',
  'Bianca Andrade',
  'Bruna Marquezine',
  'Carlinhos Maia',
  'Casimiro',
  'Danilo Gentilli',
  'Dra. Deolane',
  'Eliana',
  'Evaristo Costa',
  'Faustão',
  'Fátima Bernardes',
  'Felipe Castanhari',
  'Felipe Neto',
  'Giovana Ewbank',
  'Gisele Bündchen',
  'GKay',
  'Glória Maria',
  'Gugu Liberato',
  'Hugo Gloss',
  'Jade Picon',
  'João Guilherme',
  'Jojo Todynho',
  'Jô Soares',
  'Juliette Freire',
  'Kéfera Buchmann',
  'Larissa Manoela',
  'Lucas Guedes',
  'Lucas Rangel',
  'Luciano Huck',
  'Luva de Pedreiro',
  'Maisa',
  'Manu Gavassi',
  'Mc Mirella',
  'Marcos Mion',
  'Mari Maria',
  'Pabllo Vittar',
  'Pedro Bial',
  'Tatá Werneck',
  'Tirullipa',
  'Rafa Uccman',
  'Rafa Kalimann',
  'Raul Gil',
  'Rodrigo Faro',
  'Sabrina Sato',
  'Virgínia Fonseca',
  'Viih Tube',
  'Whinderson Nunes',
  'William Bonner',
]);

categorias.set('Personalidades internacionais', [
  'Bella Hadid',
  'Barack Obama',
  'Cara Delevingne',
  'Ellen DeGeneres',
  'Gigi Hadid',
  'Hailey Bieber',
  'James Corden',
  'James Cameron',
  'Jimmy Fallon',
  'Jeremy Clarkson',
  'Jimmy Kimmel',
  'Jeff Bezos',
  'Megan Fox',
  'Ken Block',
  'Kendall Jenner',
  'Khabane Lame',
  'Khloe Kardashian',
  'Kim Kardashian',
  'Kris Jenner',
  'Kylie Jenner',
  'Neil Degrasse Tyson',
  'Oprah Winfrey',
  'Paris Hilton',
  'Simon Cowell',
  'Steve Harvey',
  'Stephen Colbert',
  'George Lucas',
]);

categorias.set('Jogadores de futebol', [
  'Pelé',
  'Mané Garrincha',
  'Ronaldo',
  'Zico',
  'Rivelino',
  'Romário',
  'Sócrates',
  'Ronaldinho Gaúcho',
  'Jairzinho',
  'Paulo Roberto Falcão',
  'Gérson',
  'Nilton Santos',
  'Carlos Alberto Torres',
  'Leônidas da Silva',
  'Tostão',
  'Didi',
  'Júnior',
  'Clodoaldo',
  'Heleno de Freitas',
  'David Beckham',
  'Daniel Alves',
  'Gabigol',
  'Gerard Piqué',
  'Ikler Casillas',
  'James Rodríguez',
  'Kaká',
  'Luis Alberto Suárez',
  'Luka Modrić',
  'Maradona',
  'Mesut Özil',
  'Roberto Carlos',
  'Ronaldo Fenômeno',
  'Sergio Ramos',
  'Thomas Müller',
  'Zidane',
  'Lionel Messi',
  'Kylian Mbappé',
  'Karim Benzema',
  'Erling Haaland',
  'Luka Modric',
  'Kevin De Bruyne',
  'Robert Lewandowski',
  'Vinícius Júnior',
  'Thibaut Courtois',
  'Mohamed Salah',
  'Sadio Mané',
  'Neymar',
  'Harry Kane',
  'Jude Bellingham',
  'Casemiro',
  'Achraf Hakimi',
  'Antoine Griezmann',
  'Federico Valverde',
  'Pedri',
  'Emiliano Martínez',
  'Enzo Fernández',
  'Bukayo Saka',
  'Rafael Leão',
  'Phil Foden',
  'Jamal Musiala',
  'Son Heung-min',
  'Virgil van Dijk',
  'Bruno Fernandes',
  'Bernardo Silva',
  'Olivier Giroud',
  'Josko Gvardiol',
  'Julián Álvarez',
  'Christopher Nkunku',
  'Alisson',
  'Martin Ødegaard',
  'João Cancelo',
  'Gavi',
  'Ángel Di María',
  'Toni Kroos',
  'Khvicha Kvaratskhelia',
  'Joshua Kimmich',
  'David Alaba',
  `Yassine "Bono" Bounou`,
  'Rúben Dias',
  'Aurélien Tchouaméni',
  'Theo Hernández',
  'Alexis Mac Allister',
  'Rodrigo De Paul',
  'Sofyan Amrabat',
  'Cody Gakpo',
  'Cristiano Ronaldo',
  'Victor Osimhen',
  'Rodri',
  'Ederson',
  'Ilkay Gündogan',
  'Antonio Rüdiger',
  'Riyad Mahrez',
  'Marcus Rashford',
  'Luis Díaz',
  'Trent Alexander-Arnold',
  'Richarlison',
  'Gabriel Jesus',
  'Hakim Ziyech',
  'Alphonso Davies',
  'Marquinhos',
  'Dusan Vlahovic',
  'Éder Militão',
  'Marcelo Brozovic',
  'Ousmane Dembélé',
  'Lautaro Martínez ',
  'Dominik Livakovic',
  'Cristian Romero',
  'Nicoló Barella',
  'Mike Maignan',
  'Thiago Silva',
  'Hugo Lloris',
  'Fabinho',
  'Mehdi Taremi',
  'Azzedine Ounahi',
  'Kalidou Koulibaly',
  'Lisandro Martínez',
  'Darwin Núñez',
  'Aleksandar Mitrovic',
  'Kyle Walker',
  'Raphaël Varane',
  'Dayot Upamecano',
  'Ciro Immobile',
  'Declan Rice',
  'Frenkie de Jong',
  'Bruno Guimarães',
  'Manuel Neuer',
  'Giorgian de Arrascaeta ',
  'Rodrygo',
  'Reece James',
  'Serge Gnabry',
  'Sandro Tonali',
  'Andrew Robertson',
  'Leroy Sané',
  'Gabriel Barbosa',
  'Nicolás Otamendi',
]);

categorias.set('Personagens de animação', [
  'Alex, o Leão',
  'A Noiva Cadáver',
  'Ariel',
  'Alladin',
  'Alice',
  'Alegria',
  'Audrey Ramirez',
  'Alameda Slim',
  'Ben 10',
  'Baymax',
  'Bart Simpson',
  'Beetty Boop',
  'Boo',
  'Bob Esponja',
  'Bela',
  'Bela Ardomecida',
  'Branca de Neve',
  'Buzz Lightyear',
  'Cascão',
  'Capitão Gancho',
  'Capitão Jack Sparrow',
  'Cebolinha',
  'Cinderela',
  'Conserta Félix Jr.',
  'Cruella de Vil',
  'Charlie Brown',
  'Cosmo',
  'Ciborgue',
  'Kuzco',
  'Daphne',
  'Detona Ralph',
  'Diego',
  'Docinho',
  'Edna Moda',
  'Elsa',
  'Estelar',
  'Ernesto de la Cruz',
  'Florzinha',
  'Flecha Pêra',
  'Frajola',
  'Fred Flinstone',
  'Flynn Ryder',
  'Gato Félix',
  'Gasparzinho',
  'Gelado',
  'Galinho Chicken Little',
  'Glória, o Hipopótamo',
  'Hades',
  'Héctor',
  'Hércules',
  'Homer Simpson',
  'He-Man',
  'Jerry',
  'Kida',
  'Kronk',
  'Kenai',
  'Koda',
  'Leôncio',
  'Linguado',
  'Lindinha',
  'Lisa Simpson',
  'Lula Molusco',
  'Manny',
  'Maui',
  'Macaco Louco',
  'Magali',
  'Marty, a Zebra',
  'Medo',
  'Merida',
  'Mestre Shifu',
  'Mégara',
  'Melman, a Girafa',
  'Miguel',
  'Mike Wazowski',
  'Mickey Mouse',
  'Minnie Mouse',
  'Milo Thatch',
  'Mestre dos Magos',
  'Mônica',
  'Moana',
  'Mulan',
  'Mutano',
  'Mulher Elástica',
  'Nojinho',
  'Olaf',
  'Pantera cor-de-rosa',
  'Patolino',
  'Patrick Estrela',
  'Pernalonga',
  'Pica-Pau',
  'Piu-Piu',
  'Po',
  'Popeye',
  'Pateta',
  'Pacha',
  'Peter Pan',
  'Pluto',
  'Puro Osso',
  'Pricesa Jasmine',
  'Princesa Tiana',
  'Pocahontas',
  'Robin',
  'Raiva',
  'Ravena',
  'Rapunzel',
  'Rei Tritão',
  'Rei Doce',
  'Rei Julien',
  'Relâmpago Mcqueen',
  'Salsicha',
  'Sitka',
  'Scar',
  'Sid',
  'Sininho',
  'Síndrome',
  'Sr Incrível',
  'Scooby-Doo',
  'Stitch',
  'Tai Lung',
  'Tarzan',
  'Timmy Turner',
  'Tigresa',
  'Toninho Rodrigues',
  'Tristeza',
  'Ursinho Pooh',
  'Úrsula',
  'Velma',
  'Vingador',
  'Violeta',
  'Vincenzo Santorini',
  'Vanellope Von Schweetz',
  'Xerife Woody',
  'Yzma',
  'Zé Colmeia',
  'Zezé',
  'Zurg',
  'Zeca Urubu',
]);

export { categorias };
