export type Question = {
    q: string,
    a: number,
}

export const questions: Question[] = [
    {q: 'O coliseu romano foi construído?', a: 75},
    {q: 'O vulcão vesúvio destruiu Pompéia?', a: 79},
    {q: 'Foi inventado o óculos?', a: 1249},
    {q: 'Foi inventada a lupa?', a: 1250},
    {q: 'Gutemberg inventou a imprensa?', a: 1430},
    {q: 'Da Vinci pintou a Mona Lisa?', a: 1503},
    {q: 'Nasceu Nostradamus?', a: 1503},
    {q: 'Foi inventado o vaso sanitário?', a: 1596},
    {q: 'Foi inventado o telescópio?', a: 1608},
    {q: 'O dodô foi extinto?', a: 1662},
    {q: 'Foi inventada a panela de pressão?', a: 1679},
    {q: 'Foi inventada a máquina a vapor?', a: 1690},
    {q: 'Morreu o pirata Barba Negra?', a: 1718},
    {q: 'Nasceu o artista Aleijadinho?', a: 1738},
    {q: 'Foi inventado o balão de ar quente?', a: 1783},
    {q: 'Foi inventado o despertaodr?', a: 1787},
    {q: 'Ocorreu a Queda da Bastilha?', a: 1789},
    {q: 'Foi construída a Casa Branca?', a: 1792},
    {q: 'Foi inventada a pilha?', a: 1800},
    {q: 'A Família Real Portuguesa veio ao Brasil?', a: 1808},
    {q: 'Foi inventada a bibicleta?', a: 1817},
    {q: `Mary Shelley escreveu 'Frankenstein'?`, a: 1818},
    {q: 'Ocorreu o primeiro assalto a banco?', a: 1831},
    {q: 'Foi inventado o telégrafo?', a: 1837},
    {q: 'Foi inventada a anestesia?', a: 1846},
    {q: 'Foi descoberto o planeta Netuno?', a: 1846},
    {q: `Darwin Publicou 'A Origem das Espécies'?`, a: 1859},
    {q: 'Foi inventado o aspirador de pó?', a: 1869},
    {q: 'Foi descoberto o DNA?', a: 1869},
    {q: `Foi publicado 'Vinte Mil Léguas Submarinas'?`, a: 1870},
    {q: `Foi publicado 'A Ilha do Tesouro'?`, a: 1883},
    {q: 'Foi inaugurada a Estátua da Liberdade?', a: 1886},
    {q: 'Foi inventado o automóvel?', a: 1886},
    {q: 'Foi publicado Sherlock Holmes?', a: 1887},
    {q: 'Tesla patenteou o motor de indução?', a: 1888},
    {q: 'Foi inaugurada a Torre Eiffel?', a: 1889},
    {q: 'Nasceu Charles Chaplin?', a: 1889},
    {q: 'Foi inventada a garrafa térmica?', a: 1892},
    {q: 'Foi montada a primeira roda gigante?', a: 1893},
    {q: 'Foi descoberta a radioatividade?', a: 1896},
    {q: 'Foi inventado o ar condicionado?', a: 1902},
    {q: 'Foi inventado o radar?', a: 1904},
    {q: 'Ocorreu o primeiro voo do 14 Bis?', a: 1906},
    {q: 'Nasceu Frida Kahlo?', a: 1907},
    {q: `Foi publicado 'O Fantasma da Ópera?'`, a: 1910},
    {q: 'Foi patenteado o secador de cabelo portátil?', a: 1911},
    {q: 'O Titanic afundou?', a: 1912},
    {q: 'Foi descoberta a Penicilina?', a: 1928},
    {q: `Tarsila do Amaral pintou 'Abaporu'?`, a: 1928},
    {q: 'Foi inaugurado o primeiro prédio do Brasil?', a: 1929},
    {q: 'Surgiu a marca Ferrari?', a: 1929},
    {q: 'Foi inaugurado o Empire State Building?', a: 1931},
    {q: 'Carmem Miranda atuou em seu primeiro filme?', a: 1932},
    {q: 'Surgiu a chave Phillips?', a: 1934},
    {q: `Foi lançado o primeiro filme 'O mágico de Oz'?`, a: 1939},
    {q: 'Voou o primeiro avião a jato?', a: 1939},
    {q: 'Foi patenteado o plástico PET?', a: 1941},
    {q: 'A tecnologia Wi-Fi foi desenvolvida?', a: 1942},
    {q: 'Nasceu o cantor Tim Maia?', a: 1942},
    {q: 'Foi inventado o Transistor?', a: 1947},
    {q: `George Orwell publicou o livro '1984'?`, a: 1949},
    {q: 'Foi inaugurado o estádio do Maracanã?', a: 1950},
    {q: `Foi lançado o livro 'O Senhor dos Aneis'?`, a: 1954},
    {q: 'Marlon Brando ganhou seu primeiro Oscar?', a: 1955},
    {q: 'Ocorreu o pior acidente da história do automobilismo?', a: 1955},
    {q: 'Nasceu o ator Tom Hanks?', a: 1956},
    {q: 'A cadela Laika foi enviada ao espaço?', a: 1957},
    {q: 'A primeira peça de Lego foi patenteada?', a: 1958},
    {q: 'O Brasil ganhou a primeira copa?', a: 1958},
    {q: `Martin Luther King discursou 'I Have a Dream?'`, a: 1963},
    {q: 'Ocorreu o primeiro transplante de coração?', a: 1964},
    {q: 'Pelé marcou o milésimo gol?', a: 1969},
    {q: 'O homem pisou na lua?', a: 1969},
    {q: 'A balinha Tic Tac foi lançada?', a: 1970},
    {q: 'A TV colorida chegou ao Brasil', a: 1972},
    {q: 'Foi lançado o jogo WAR?', a: 1972},
    {q: 'Foi inventado o cubo mágico?', a: 1974},
    {q: 'João Paulo II foi eleito Papa?', a: 1978},
    {q: `Foi formada a banda 'Red Hot Chili Peppers'?`, a: 1979},
    {q: 'Denzel Washington atuou em seu primeiro filme?', a: 1981},
    {q: 'Surgiu o notebook?', a: 1982},
    {q: 'Se passa a primeira temporada de Stranger Things?', a: 1983},
    {q: `Foi criado o Cirque Du Soleil?`, a: 1984},
    {q: 'Ocorreu o acidente nuclear de Chernobyl?', a: 1986},
    {q: 'Michael Schumacher entrou na Fórmula 1?', a: 1991},
    {q: 'Ayrton Senna virou tricampeão da F1?', a: 1991},
    {q: `Lançou o filme 'Carlota Joaquina - Princesa do Brasil'?`, a: 1995},
    {q: 'O Bluetooth foi lançado?', a: 1999},
    {q: 'Foi a primeira copa do mundo de Ronaldinho Gaúcho?', a: 2002},
    {q: `A banda Rouge lançou a música 'Ragatanga'?`, a: 2002},
    {q: 'Beyoncé lançou a música Single Ladies?', a: 2008},
    {q: 'Foi lançado o jogo League of Legends?', a: 2009},
    {q: 'Estreou a primeira temporada de Game of Thrones?', a: 2011},
    {q: `Foi lançado o filme '1917'?`, a: 2019},
]