export type Question = {
    q: string,
    a: number,
}

export const questions: Question[] = [
    {q: 'O coliseu romano foi construído?', a: 75},
    {q: 'O vulcão vesúvio destruiu Pompéia?', a: 79},
    {q: 'Foi inventado o óculos?', a: 1249},
    {q: 'Gutemberg inventou a imprensa?', a: 1430},
    {q: 'Da Vinci pintou a Mona Lisa?', a: 1503},
    {q: 'Foi inventado o vaso sanitário?', a: 1596},
    {q: 'Foi inventado o telescópio?', a: 1608},
    {q: 'O dodô foi extinto?', a: 1662},
    {q: 'foi inventada a máquina a vapor?', a: 1690},
    {q: 'Ocorreu a Queda da Bastilha?', a: 1789},
    {q: 'Foi inventada a pilha?', a: 1800},
    {q: 'A Família Real Portuguesa veio ao Brasil?', a: 1808},
    {q: 'Foi inventada a bibicleta?', a: 1817},
    {q: `Mary Shelley escreveu 'Frankenstein'?`, a: 1818},
    {q: 'Ocorreu o primeiro assalto a banco?', a: 1831},
    {q: 'Foi inventado o telégrafo?', a: 1837},
    {q: 'Foi inventada a anestesia?', a: 1846},
    {q: `Darwin Publicou 'A Origem das Espécies'?`, a: 1859},
    {q: 'Foi inventado o aspirador de pó?', a: 1869},
    {q: 'Foi descoberto o DNA?', a: 1869},
    {q: `Foi publicado 'Vinte Mil Léguas Submarinas'?`, a: 1870},
    {q: `Foi publicado 'A Ilha do Tesouro'?`, a: 1883},
    {q: 'Foi inaugurada a Estátua da Liberdade?', a: 1886},
    {q: 'Foi inventado o automóvel?', a: 1886},
    {q: 'Foi publicado Sherlock Holmes?', a: 1887},
    {q: 'Tesla patenteou o motor de indução?', a: 1888},
    {q: 'Foi inaugurada a Torre Eiffel?', a: 1889},
    {q: 'Foi descoberta a radioatividade?', a: 1896},
    {q: 'Ocorreu o primeiro voo do 14 Bis?', a: 1906},
    {q: 'Foi patenteado o secador de cabelo portátil?', a: 1911},
    {q: 'Foi inaugurado o primeiro prédio do Brasil?', a: 1929},
    {q: 'Surgiu a marca Ferrari?', a: 1929},
    {q: 'Voou o primeiro avião a jato?', a: 1939},
    {q: 'Foi patenteado o plástico PET?', a: 1941},
    {q: 'A tecnologia Wi-Fi foi desenvolvida?', a: 1942},
    {q: 'Foi inventado o Transistor?', a: 1947},
    {q: `George Orwell publicou o livro '1984'?`, a: 1949},
    {q: 'A cadela Laika foi enviada ao espaço?', a: 1957},
    {q: 'A primeira peça de Lego foi patenteada?', a: 1958},
    {q: 'O Brasil ganhou a primeira copa?', a: 1958},
    {q: 'Ocorreu o primeiro transplante de coração?', a: 1964},
    {q: 'Pelé marcou o milésimo gol?', a: 1969},
    {q: 'O homem pisou na lua?', a: 1969},
    {q: 'Foi inventado o cubo mágico?', a: 1974},
    {q: 'Surgiu o notebook?', a: 1982},
    {q: 'Se passa a primeira temporada de Stranger Things?', a: 1983},
    {q: `Foi criado o Cirque Du Soleil?`, a: 1984},
    {q: 'Ocorreu o acidente nuclear de Chernobyl?', a: 1986},
    {q: 'Ayrton Senna virou tricampeão da F1?', a: 1991},
    {q: 'Beyoncé lançou a música Single Ladies?', a: 2008},
    {q: 'Foi lançado o jogo League of Legends?', a: 2009},
]