const categories: Map<string, string[]> = new Map();

categories.set('Animais', [
  'Abelha',
  'Águia',
  'Arara',
  'Aranha',
  'Bacalhau',
  'Barata',
  'Baleia',
  'Borboleta',
  'Cachorro',
  'Camarão',
  'Camelo',
  'Canguru',
  'Cavalo',
  'Centopéia',
  'Cisne',
  'Cobra',
  'Crocodilo',
  'Coruja',
  'Elefante',
  'Escorpião',
  'Falcão',
  'Flamingo',
  'Formiga',
  'Gafanhoto',
  'Galinha',
  'Gambá',
  'Gato',
  'Girafa',
  'Golfinho',
  'Gorila',
  'Hiena',
  'Hipopótamo',
  'Jacaré',
  'Lagarto',
  'Leão',
  'Macaco',
  'Mamute',
  'Minhoca',
  'Morcego',
  'Mosca',
  'Ovelha',
  'Panda',
  'Pato',
  'Piranha',
  'Porco',
  'Preguiça',
  'Rato',
  'Siri',
  'Tartaruga',
  'Tigre',
  'Touro',
  'Vaca',
  'Veado',
  'Zebra',
]);

// categories.set('Personagens', [
//     'Ariel',
//     'Alladin',
//     'Alice',
//     'Andrômeda',
//     'Baymax',
//     'Bela',
//     'Bela Ardomecida',
//     'Branca de Neve',
//     'Buzz Lightyear',
//     'Capitão Gancho',
//     'Capitão Jack Sparrow',
//     'Cinderela',
//     'Conserta Félix Jr.',
//     'Cruella de Vil',
//     'Detona Ralph',
//     'Elsa',
//     'Hades',
//     'Hércules',
//     'Kida',
//     'Merida',
//     'Mike Wazowski',
//     'Mickey Mouse',
//     'Minnie Mouse',
//     'Milo Thatch',
//     'Moana',
//     'Mulan',
//     'Olaf',
//     'Pateta',
//     'Peter Pan',
//     'Pluto',
//     'Pricesa Jasmine',
//     'Princesa Tiana',
//     'Pocahontas',
//     'Rapunzel',
//     'Relâmpago Mcqueen',
//     'Scar',
//     'Stitch',
//     'Sininho',
//     'Tarzan',
//     'Ursinho Pooh',
//     'Úrsula',
//     'Xerife Woody',
//     'Bart Simpson',
//     'Beetty Boop',
//     'Bob Esponja',
//     'Charlie Brown',
//     'Cosmo',
//     'Daphne',
//     'Docinho',
//     'Florzinha',
//     'Frajola',
//     'Fred Flinstone',
//     'Gato Félix',
//     'Gasparzinho',
//     'Homer Simpson',
//     'He-Man',
//     'Jerry',
//     'Lindinha',
//     'Lisa Simpson',
//     'Lula Molusco',
//     'Macaco Louco',
//     'Magali',
//     'Mestre dos Magos',
//     'Mônica',
//     'Pantera cor-de-rosa',
//     'Patolino',
//     'Patrick Estrela',
//     'Pernalonga',
//     'Pica-Pau',
//     'Piu-Piu',
//     'Popeye',
//     'Salsicha',
//     'Scooby-Doo',
//     'Timmy Turner',
//     'Ursinho Pooh',
//     'Velma',
//     'Vingador',
//     'Zé Colmeia',
// ]);

categories.set('Objetos', [
  'Abajur',
  'Bacia',
  'Cama',
  'Dentadura',
  'Espelho',
  'Faca',
  'Garfo',
  'Helicóptero',
  'Igreja',
  'Joia',
  'Lápis',
  'Martelo',
  'Navalha',
  'Óculos',
  'Prato',
  'Rádio',
  'Sandália',
  'Torneira',
  'Uva',
  'Vaso',
  'Xadrez',
  'Zodíaco',
]);

export { categories };
